FROM ubuntu:16.04

RUN apt-get update -y \
    && apt-get install curl -y \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install nodejs -y


COPY car-statistics/app/static/package.json /car-statistics/app/static/package.json
WORKDIR /car-statistics/app/static/

RUN npm install \
    &&npm install -g @angular/cli
