"""subsets table

Revision ID: 4b6e16855d09
Revises: fb4498027e47
Create Date: 2018-09-13 16:06:03.667022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b6e16855d09'
down_revision = 'fb4498027e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('hash_name', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('file_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subsets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subset_name', sa.String(), nullable=False),
    sa.Column('hash_name', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('subset_rel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['subset_rel'], ['subsets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('file_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_user_id'], ['users.id'], name='users_files_file_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_files_pkey')
    )
    op.drop_table('subsets')
    op.drop_table('files')
    # ### end Alembic commands ###
