"""empty message

Revision ID: 8568ee529e5e
Revises: 269e33d2bf93
Create Date: 2018-09-15 20:02:13.514011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8568ee529e5e'
down_revision = '269e33d2bf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_date')
    # ### end Alembic commands ###
