"""empty message

Revision ID: faa6795b95fb
Revises: 4b6cbbf88bc4
Create Date: 2018-09-15 20:11:12.968669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faa6795b95fb'
down_revision = '4b6cbbf88bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_date', sa.DateTime(), nullable=True))
    op.alter_column('users', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'confirmed_date')
    # ### end Alembic commands ###
