"""empty message

Revision ID: d3fb426073dc
Revises: 1df858ca1ee9
Create Date: 2018-09-20 15:34:52.153026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fb426073dc'
down_revision = '1df858ca1ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_file_id_fkey', 'dataset', type_='foreignkey')
    op.create_foreign_key(None, 'dataset', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.create_foreign_key('dataset_file_id_fkey', 'dataset', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
